### ISSUE TITLE
Navbar buttons styling 

### ISSUE THREAD

**Issue by RishabhJain0721** [Priyanshu85/Webtools#19]
![Screenshot 2022-10-07 145258](https://user-images.githubusercontent.com/107767172/194523187-a8d52885-d808-45e3-a598-332121824e86.png)
### Hi
Hovering on the left and rightmost sides of "TOOLS" button is turning whole button black.
Moreover the hovering effects of "HOME" and "CONTACT US" buttons aren't looking very good.
Let me fix them ; assign this task to me.

**Comment by Priyanshu85** [comment]
Nice bug bro....On you!

**Comment by RishabhJain0721** [comment]
@Priyanshu85 I have made a PR please review it

**Comment by Priyanshu85** [comment]
Yup Merged Bro... Thanks!!
