### ISSUE TITLE
Errors 404

### ISSUE THREAD

**Issue by Oussamaosman02** [Priyanshu85/Webtools#22]
Failed to load resource: the server responded with a status of 404()

This error is thrown 3 times for two different files.

Easy to fix, if you want you can fix it by yourself or assign it to me.

**Comment by Priyanshu85** [comment]
For which files you are getting this error??

**Comment by Oussamaosman02** [comment]
Is for `styles.css` and `particle.json`
If you inspect the main page you will see this errorrs

**Comment by Priyanshu85** [comment]
Okay Cool Gotchaa!!!...Very small kinda work...but will assign you to do that so that you can have a pull in hacktober!!
Happy Hacking!!
