### ISSUE TITLE
Title: Random Joke Generator using API

### ISSUE THREAD

**Issue by Atharv-110** [Priyanshu85/Webtools#37]
## Problem Description
At times a person with a heavy workload forgets to take a break. So to relax his/her mind for a short period of time only.
He could use online tools like Joke Generator App, etc.

## Solution:-
I want to add a web tool known as Joke Generator App which will fetch the jokes and displays them to the user.

## Technologies:-
1. HTML
2. CSS
3. JavaScript

**Comment by VedantBandeJain** [comment]
can u assign this to me I would like to make such thing
.

**Comment by Atharv-110** [comment]
@Priyanshu85 #45 PR resolves this Issue
