### ISSUE TITLE
Title: Text to Speech Convertor

### ISSUE THREAD

**Issue by Atharv-110** [Priyanshu85/Webtools#42]
Hey @Priyanshu85 ,
I would like to add a web app made using JavaScript that converts any text into speech and narrates it.
Tech Stack:
-HTML
-CSS
-JS
Consider this contribution under Hacktoberfest 2022 and add tags of hacktoberfest.
Thank You.

**Comment by Priyanshu85** [comment]
Okay...On you @Atharv-110
