### ISSUE TITLE
Title: Captcha Code Generator

### ISSUE THREAD

**Issue by Atharv-110** [Priyanshu85/Webtools#43]
Hey @Priyanshu85,
I would like to add a captcha code generator that generates a captcha code that could be used by many people for verification and authentication.
Tech Stack:
- HTML
- CSS
- JS

### Please consider and assign it to me under hacktoberfest 2022 and add hacktoberfest tags.
Thank You

**Comment by Priyanshu85** [comment]
Coool...go for it!! @Atharv-110

**Comment by Vedant003** [comment]
Hello @Priyanshu85 can you please assign me the task?

**Comment by Priyanshu85** [comment]
Please choose a different task @Atharv-110 is already doing it!!

> Hello @Priyanshu85 can you please assign me the task?

**Comment by Atharv-110** [comment]
This issue would be Resolved via #52 no. PR

**Comment by Priyanshu85** [comment]
Merged!
