### ISSUE TITLE
Heading will look better in the center

### ISSUE THREAD

**Issue by samitkapoor** [Priyanshu85/Webtools#47]
The Heading "OUR TOOLS" will look better if it was in the center aligned with the screen.

![webtools](https://user-images.githubusercontent.com/77121931/194718904-28cc5add-f66c-499e-bf4d-4d15b09963a6.png)

**Comment by jsvigneshkanna** [comment]
Hey @Priyanshu85 , @samitkapoor 

I would like do these changes. please assign this issue to my name

Appreciate that!

**Comment by Priyanshu85** [comment]
Assigned bruh @jsvigneshkanna
