### ISSUE TITLE
The input cursor should get enabled as soon as the "Start" button is pressed in the Typing Speed test tool

### ISSUE THREAD

**Issue by samitkapoor** [Priyanshu85/Webtools#48]
When I press the Start button, I also have to click on the text field before entering the text that appears, this wastes 1-2 seconds and my typing speed analysis is not 100% accurate.

![image](https://user-images.githubusercontent.com/77121931/194719103-81e722bd-4e26-40f8-bcc6-7440adaa787a.png)

**Comment by jsvigneshkanna** [comment]
Hi @Priyanshu85 @samitkapoor ,
I would like to do these changes. Please assign me this issue under my name.

Appreciate that!

**Comment by Priyanshu85** [comment]
done bruh @jsvigneshkanna
