### ISSUE TITLE
Update Favicon and title

### ISSUE THREAD

**Issue by jsvigneshkanna** [Priyanshu85/Webtools#50]
Hey 👋, @Priyanshu85 

I would like to 

1. add new favicon which denotes a spanner/ laptop (tool) image.
2. Update the website title to smaller case to maintain standards (Webtools)

Please assign this issue to my name.
Please add `hacktoberfest` label so that I can keep track of my contributions this month

Appreciate that!

**Comment by Priyanshu85** [comment]
On you bruh @jsvigneshkanna
