### ISSUE TITLE
Page header is not responsive

### ISSUE THREAD

**Issue by Ezekiel8807** [Priyanshu85/Webtools#63]
The page header should be responsive and every elements in the 
[webtools](https://webtools-kitretsu.netlify.app/)

**Comment by Priyanshu85** [comment]
Yeahh...there is an issue for that to make the page responsive...should I assign you this here? @Ezekiel8807

**Comment by Ezekiel8807** [comment]
Sure you can

**Comment by Priyanshu85** [comment]
Done!!
Make the Page as Responsive as POssible

**Comment by Ezekiel8807** [comment]
have made a PR to handle #76. i need it to be merged. So i can make a PR for making other parts of the page responsive
